# Generated by Django 5.1 on 2024-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_remove_issue_status_issue_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='completed',
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in-progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
