# Generated by Django 5.1 on 2024-09-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0012_remove_issue_status_todolist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='status',
        ),
    ]
