# Generated by Django 5.1 on 2024-09-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0014_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
