# Generated by Django 5.1 on 2024-09-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0018_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodolistFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to='todoattachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task_management.todolist')),
            ],
        ),
    ]
