# Generated by Django 5.1 on 2024-10-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0027_task_comment_timestamp_task_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment_timestamp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
    ]
