# Generated by Django 5.1 on 2024-10-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0032_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Working', 'Working'), ('Pending Review', 'Pending Review'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rework', 'Rework')], default='Not Started', max_length=20),
        ),
    ]
