# Generated by Django 5.1 on 2024-10-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0033_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
