# Generated by Django 5.1 on 2024-10-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0037_task_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
    ]
