# Generated by Django 5.1 on 2024-12-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0044_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_as_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_as_working',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
