# Generated by Django 5.1 on 2025-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0045_task_updated_as_completed_task_updated_as_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('organiser', models.CharField(max_length=200)),
                ('partner', models.CharField(default='none', max_length=200)),
                ('partner_logo', models.URLField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
                ('actual_starttime', models.TimeField(null=True)),
                ('actual_endtime', models.TimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('actual_duration', models.DurationField(null=True)),
                ('agenda', models.JSONField(default=list)),
                ('remark', models.JSONField(default=list)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
