# Generated by Django 5.1 on 2024-11-01 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Loss Of pay', 'Loss Of pay'), ('Comp-Off', 'Comp-Off'), ('Sick Leave probation', 'Sick Leave probation'), ('Optional Holiday', 'Optional Holiday')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('session_from', models.CharField(choices=[('Session 1', 'Session 1'), ('Session 2', 'Session 2')], max_length=50)),
                ('session_to', models.CharField(choices=[('Session 1', 'Session 1'), ('Session 2', 'Session 2')], max_length=50)),
                ('reason', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
