# Generated by Django 5.1 on 2024-11-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
