# Generated by Django 5.1 on 2024-11-05 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_management', '0002_leaverequest_current_level_leaverequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='level1_approvers',
            field=models.ManyToManyField(blank=True, related_name='level1_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='level2_approvers',
            field=models.ManyToManyField(blank=True, related_name='level2_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='level3_approvers',
            field=models.ManyToManyField(blank=True, related_name='level3_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
