# Generated by Django 5.1 on 2024-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_management', '0006_sentemail_recipient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
